### ISSUE TITLE
Issue when building on Mac

### ISSUE THREAD

**Issue by Hyperson** [dekzitfz/generator-code-base-android#9]
Since Mac OS see files that start with "." as hidden, the build fails when it tries to copy the .gitignore to the created folder

Suggestion:
I would suggest to handle this on both `exports.copy = function (from, to, options)` and `exports._copySingle = function (from, to, options)` methodes in copy.js

**Comment by dekzitfz** [comment]
decided to not copying .gitignore, you can create your own .gitignore

afbb4ab11cd108aa393a2515c78a150f874486d3
